User:
  name: cip
  role: tech
  type: pwm sequence

DAQ:
  name: Nano
  port: /dev/ttyUSB0


Sequence:
  channel: '05'
  start: 0
  stop: 255
  step: 5
  delay: 500

Flasher:
  channel: '05'
  ton: 100
  toff: 500
  count: 10

Save_File:
  filename: data.dat # Files won't be overwritten, but renamed as data_001.dat, etc.

GUI:
  refresh_time: 100ms
